openLoopDepth: false
openLoopDepthSpeed: -6.0 #only used when openLoopDepth = true
closeLoopDepth: 1.00     #only used when openLoopDepth = false

surgeSpeed: -3.0

#Timeouts
yawTimeout: 5.0
openLoopDepthTimeout: 10.0
closeLoopDepthTimeout: 15.0
gateTimeout: 20.0      #IMPORTANT parameter to tweak to avoid doing line too early(before finishing gate) or too late(no longer seeing line)

#Bounds for close loop setPoints for lane
xBound: 0.1;
yBound: 0.1;
yawBound: 0.1;
pitchBound: 0.1;